name: "Nueva Accion"
desciption: "Test para nueva accion"

inputs:
  message:
    description: "The message to print"
    required: true
    default: "Hola"

runs:
  using: "composite"

  steps:
    - name: Hola Mundo
      run: echo "Hola Mundo"
      shell: bash
    - name: Hola input
      run: echo "Hola $ {{inputs.message}}"
      shell: bash
