name: Main

on: [push]

jobs: 
  test-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: multiline
        run: |
          echo "Que tal Mundo" >> hola.txt
          cat hola.txt
      - name: Curl
        run: |
          chmod +x script.sh
          ./script.sh

