name: Ejemplo de Composite Action

on: [push]

jobs:
  say-hello:
    runs-on: ubuntu-latest

    env:
      MY_VAR: Prueba de mi variable

    steps:
      - name: Test env
        run: echo "Valor $MY_VAR"
